local f = CreateFrame("Frame")
f:RegisterEvent("PLAYER_ENTERING_WORLD")
f:SetScript("OnEvent", function()
  DEFAULT_CHAT_FRAME:AddMessage("This is addon6, I loaded successfully and am ready to go!")
end)